[package]
name = "hackerman"
version = "0.1.0"
authors = ["Shiv Bhatia <shivbhatia10@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
rand    = "*"
transpose = "0.2.0"
